### ISSUE TITLE
Update online version

### ISSUE THREAD

**Issue by feliixx** [IanWhalen/mongodb-tools.com#160]
The version currently deployed at [http://mongodb-tools.com/](http://mongodb-tools.com/) does not contain last updates from Sept/Oct 2017. Last change of the online version seems to be [this commit](https://github.com/IanWhalen/mongodb-tools.com/commit/3cb199cee324cd54c91f0248446ded650f6bd206)

Is this expected ?

**Comment by stennie** [comment]
@feliixx Apologies for the delayed follow-up. An updated version has now been deployed on mongodb-tools.com :).

The online version is deployed manually, but should be refreshed reasonably soon after changes have been committed. My last round of changes updated Jekyll & bundler requirements which unfortunately led to some unexpected [yak shaving](https://en.wiktionary.org/wiki/yak_shaving#Noun0) in order for Ian to update his environment and deploy. It took a while to find the round tuits, but future updates should be more timely.

Regards,
Stennie
