### ISSUE TITLE
Add "REST Interface" category

### ISSUE THREAD

**Issue by stennie** [IanWhalen/mongodb-tools.com#41]
Examples: http://docs.mongodb.org/ecosystem/tools/http-interfaces/

**Comment by nicolaiarocci** [comment]
Yes please so I can then add python-eve.org :smile:

**Comment by stennie** [comment]
@nicolaiarocci Do you want to go ahead a submit a PR with for Eve with "REST Interface" as the purpose? I'll work on adding more :)

**Comment by nicolaiarocci** [comment]
Done! #48
