### ISSUE TITLE
Add "Schema Analysis" purpose

### ISSUE THREAD

**Issue by stennie** [IanWhalen/mongodb-tools.com#43]
Known list to start with:
- https://github.com/mongodb-js/mongodb-schema (open source)
- https://github.com/variety/variety (open source)
- https://github.com/skratchdot/mongodb-schema/ (open source)
- https://github.com/izmailoff/MongoDB-Schema-Analyzer (open source)
- https://github.com/imlucas/mongodb-infer (open source)
- http://3t.io/schema-explorer (commercial)
- http://jsonstudio.com/mongodb-data-access-tools/ (commercial)

**Comment by IanWhalen** [comment]
makes sense to me.
