### ISSUE TITLE
Consider renaming "GUI" to "Data Management UI"

### ISSUE THREAD

**Issue by stennie** [IanWhalen/mongodb-tools.com#46]
GUI seems too broad a term (although perhaps common for folks to search for).

I believe most of the current listings in this category are actually "Data Management UIs". They deal with viewing & editing data, but generally do not extend to server admin.

Perhaps rename to something like "Data Management UI (GUI)" to cover both?

**Comment by IanWhalen** [comment]
as discussed over email, "GUI" is a major source of organic search traffic so I'd prefer not to lose that.  The latter suggestion (Data Management UI (GUI)) seems pretty verbose.  I'm not against changing, but would like to pause until we make sure any change won't cost us.

**Comment by stennie** [comment]
How about "Data Management GUI" .. that's more specific on the intent without losing the GUI?
