### ISSUE TITLE
Add MongoHub

### ISSUE THREAD

**Issue by IanWhalen** [IanWhalen/mongodb-tools.com#52]
Used to have MongoHub listed, but dropped it when the old repo went inactive.  Looks like someone picked up development. https://github.com/jeromelebel/MongoHub-Mac

**Comment by stennie** [comment]
@IanWhalen For open source projects where the source is still available (and maybe no more than ?2? years old), I think it would be worth listing them as Inactive in case someone decides to pick up development again.

**Comment by IanWhalen** [comment]
yeah, to clarify, I pulled this one because it was >2 years old, and I only just noticed now that dev had moved to a different repo/owner.
