### ISSUE TITLE
add "active/inactive" filter please

### ISSUE THREAD

**Issue by tomByrer** [IanWhalen/mongodb-tools.com#61]
I'd like to filter out those projects that are not actively maintained anymore, since there are many per type of tool.
Anyone else?

**Comment by stennie** [comment]
@tomByrer Thanks for the suggestion .. agree that inactive tools could be better filtered and/or highlighted. It probably makes sense to hide inactive ones by default and have a filter or checkbox option to "Show All".

I think we need to do a pass through to make sure the currently listed tools are truly inactive/active, but we've made a lot of updates recently so the information should be getting better. It would probably help to have a clearer definition on "inactive" as well (no commits or releases in some number of months?).

There are also some categories where an inactive tool might still be fine (for example, Schema Analysis) but others where it is likely dangerous (Web admin UIs). For open source projects that are inactive, there's always a possibility that someone will discover & resurrect them ;-).
