### ISSUE TITLE
Add "Flashback" tool (performance tuning)

### ISSUE THREAD

**Issue by stennie** [IanWhalen/mongodb-tools.com#76]
https://github.com/ParsePlatform/flashback

**Comment by IanWhalen** [comment]
hmmm, for some reason I would swear I already had this one. did it previously go by a different name?

**Comment by stennie** [comment]
@IanWhalen Perhaps thinking of the [Dvara](http://mongodb-tools.com/tool/dvara/) connection proxy? Both were released around MongoDB World 2014 iirc.

**Comment by IanWhalen** [comment]
yeah I think I might be confusing them.  should def add flashback - I think it's super cool.
