### ISSUE TITLE
Mongo VUE Site is down 

### ISSUE THREAD

**Issue by bheemreddy181** [IanWhalen/mongodb-tools.com#96]
Hi Ian,

I was not able to access Mongo Vue.com from past two days . I was not even able to report the same to the concern admin team . Please do help me on this.

Regards
Bheem

**Comment by stennie** [comment]
@bheemreddy181 The MongoVUE application hasn't been updated for more than 2 years .. I would look for an alternative product in the GUI category that is actively maintained. In any case, the MongoDB Tools site is just a directory so if you have issues with a tool you'll have to contact the developer directly.
